version: '3.8'

services:
  api: 
    container_name: api
    dockerfile: dockerfile
    depends_on:
      - mongo
    ports:
      - "5000:80"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example